name: CI API Run tests

on:
  push:
    branches: [master]
    
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    
    strategy:
      matrix:
        node-version: [12.x] 
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Setup do Node.JS
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      
      # instalando as dependencias
      - run: npm install
      
      # executar os testes
      - run: npx cypress run
      
      # salvar screenshots em caso de falha na execucao
      - name: Upload screenshots
        uses: actions/upload-artifact@v2.2.3
        if: failure()
        with:
          name: screenshots
          path: web/cypress/screenshots          
  
      # salvar video em caso de falha na execucao
      - name: Upload videos
        uses: actions/upload-artifact@v2.2.3
        if: always()
        with:
          name: videos
          path: web/cypress/videos
